### ISSUE TITLE
Bug upon a second signup for a recurring contribution

### ISSUE THREAD

**Issue by BorislavZlatanov** [drastik/com.drastikbydesign.stripe#120]
This bug happens only when someone already has an existing active recurring contribution and they sign up for a recurring contribution again. Not sure if anyone would experience the bug because of the unusual workflow, but I thought there might be some benefits in mentioning it.

A detailed explanation and suggestion for fix follows.

You make a first recur contribution and it all works fine. Then when you make a recur contribution again, the first subscription gets deleted from stripe.com and from your site's database. And then a new subscription is created on its place. But when the subscription is deleted from stripe.com, that triggers a webhook from stripe.com that reaches your site and it causes the subscription to be deleted there as well. It deletes based on invoice ID, HOWEVER it grabs the invoice ID based on the customer ID. And the customer ID at that point in time is associated with the new invoice ID, created with the second recur contribution.

More simply and graphically, here's what happens in the civicrm_stripe_subscriptions table:
First recurring contrib:  
- subscription is inserted  
  Second recurring contrib:  
- previous subscription is deleted  
- new subscription inserted  
  Webhook on subscription deleted event:  
- the subscription that was just added gets deleted  
  Webhook on invoice paid event:  
- it can't find the subscription in the table  

The result is that the second contribution never gets a status of Completed.

A fix would be to get the code that runs upon the webhook on subscription deleted event to delete the row with the correct invoice ID. This might be done by getting the invoice ID directly from stripe.com rather than mapping it via the customer. Unfortunately, the invoice ID can't be (easily?) taken from stripe.com because on the customer.subscription.deleted event we don't have an invoice ID in the data. We have a subscription ID. This makes sense - there is a new invoice for each payment made. But the subscription ID remains the same.

A better solution seems to be to have the subscription ID (rather than invoice ID) in the civicrm_stripe_subscriptions table. Then the subscription could be easily deleted from the table.

**Comment by h-c-c** [comment]
I just added support for multiple subscriptions per customer in my fork, which addresses this issue. I'm using the code as it is in production.  I'm 8 commits behind however so I'm sorting things out before I do a PR.  I don't think It's too badly out of sync because there's some overlap in efforts.....like switching to api for recurring.    

NB: I'm not certain there is a reliable upgrade path for existing users.  In some instances of civi/stripe I've have setup and tested, _sometimes_ the subscription id ends up in the trxn_id field of a contribution.    Maybe for 1.9.1 folks it's consistently there? That way an upgrade script could add the new column to civicrm_stripe_subscriptions  and fill in all the correct subscription ids.

**Comment by drastik** [comment]
Nice work @h-c-c .

Let me know what you need from my side.  Would love to get your work brought in and rebase these 2.

**Comment by h-c-c** [comment]
Thanks @drastik! I'll be in touch.

**Comment by sgladstone** [comment]
I am experiencing this bug as well.  I am only using this in a test environment, as this issue makes Stripe unusable in a production environment.

**Comment by h-c-c** [comment]
The multiple-subscriptions-per-customer feature implemented in 6d3220d979657674b1bf7e9c373a53d034e8f956 addresses this issue.
