### ISSUE TITLE
Go back button on CiviCRM contribution page makes payment 

### ISSUE THREAD

**Issue by vincent1892** [drastik/com.drastikbydesign.stripe#144]
The go back button on civicrm contribution page makes payment only when using the strip 1.9.2 update for civi 4.6. Here are the steps I followed:
- Create new contribution page
- Amounts - Set Payment processor to Stripe
- set a Price set
- save
- View Test site of contribution page
- Fill in the required fields -> Confirm contribution
- On the summary page click Go Back
  -> It confirms that the payment was successful: "Your transaction has been processed successfully. Please print this page for your records." And the buttons disappear from screen
  ![screen shot 2016-06-30 at 11 46 15 2](https://cloud.githubusercontent.com/assets/13077149/16485992/d3179e00-3eb9-11e6-802d-9de05c72ed7d.png)

The same thing happens when registering for events using only the strip 1.9.2 version.

**Comment by parkesdesign** [comment]
I can confirm that I am having this same problem as well. I thought it was the event module but it seems to be the stripe module that is causing this problem.

**Comment by theshahidali** [comment]
Can you confirm the version of civiCRM ?

**Comment by parkesdesign** [comment]
Hi, the version is 4.7.3

_Daimian Parkes_
_IT CONSULTANT_

_PARKES DESIGN_

*Phone: *(07) 3041 1702

*Mobile: *0402 798 430

_E-mail: daimian@parkesdesign.com.au daimian@parkesdesign.com.au_

This e-mail and any files transmitted with it are confidential and may
contain privileged information. It is intended solely for the use of the
individual or entity to whom it is addressed. If you are not the addressee
it may be unlawful for you to read, copy, distribute, disclose or otherwise
use the information in this e-mail.

BEFORE PRINTING PLEASE CONSIDER THE ENVIRONMENT

**Comment by drastik** [comment]
There are new commits in the -dev branches here on GitHub which should fix this issue.

Please re-open if still a problem.

**Comment by madurak** [comment]
Hi,
I am seeing the same issue on Stripe 1.9.2, CiviCRM 4.6.21. Was the fix applied to the 4.6-dev branch as well?

**Comment by drastik** [comment]
You are correct.  PR #154 has been applied to 4.6 now.
https://github.com/drastik/com.drastikbydesign.stripe/commit/eed6ede0006058ba34dea901adccf8d25f540f90
