### ISSUE TITLE
Error: Missing required param: number

### ISSUE THREAD

**Issue by vincent1892** [drastik/com.drastikbydesign.stripe#145]
When the "make contribution" button or the "back"  button is clicked on civicrm contribution page it gives this error and remains on the page "Error: Missing required param: number"

Here are the steps I followed:

Create new contribution page
Amounts - Set Payment processor to Stripe
Make Fixed Contribution Options /at least one
Enable membership on contribution page, and give a membership type
save
View Live site of contribution page
Fill in the required fields -> Confirm contribution
On the summary page click Go Back

-> The page just refreshes itself and remains there, giving an error message: "Payment error response: Error: Missing required param: number" And instead of the Go back sign the "Make contribution" will appear.

![screen shot 2016-06-30 at 16 02 51 2](https://cloud.githubusercontent.com/assets/13077149/16495031/91e3116a-3ee3-11e6-8096-80cf73a4889b.png)

**Comment by theshahidali** [comment]
I have tested this issue, it is working fine now. This was an issue with the previous version of stripe. There was missing default declaration of parameter number. Upgrade to latest version and this will work fine.

**Comment by madurak** [comment]
Hi,
I am seeing a different issue now on the go back button. On clicking Go Back button the contribution gets submitted. There is a discussion [here](https://github.com/drastik/com.drastikbydesign.stripe/issues/144) about it being fixed in latest commits in dev branches. I tested it today on the 4.6-dev branch with latest commits and still seeing this issue. There is a fix on 4.7-dev branch - https://github.com/drastik/com.drastikbydesign.stripe/issues/154
Was it not applied to 4.6-dev?

Another issue is: On clicking Make Contribution button, both the 'make contribution' and 'go back' buttons turn into "Processing" button.
![screen shot 2016-09-30 at 10 51 30](https://cloud.githubusercontent.com/assets/10810117/18990578/cf3f90b4-870a-11e6-8ab0-0cc7998b6740.png)

**Comment by drastik** [comment]
@madurak Can you confirm the "Go Back" button has class `cancel` on your site?

**Comment by madurak** [comment]
Not a developer, but does this answer ->
![screen shot 2016-09-30 at 16 13 04](https://cloud.githubusercontent.com/assets/10810117/18996613/e1811c02-8728-11e6-8680-d93db426829f.png)

**Comment by drastik** [comment]
Perfect, thanks!  It does have the `cancel` class.  
PR #154 has been applied to 4.6 now.
https://github.com/drastik/com.drastikbydesign.stripe/commit/eed6ede0006058ba34dea901adccf8d25f540f90
