### ISSUE TITLE
Typo in update 1903 code - MUL?

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#191]
I recently upgraded to CiviCRM 4.7 from 4.4. During the upgrade I see the following in my logs:
Feb 24 07:22:46  [info] Running task: Upgrade com.drastikbydesign.stripe to revision 1_9_003
Feb 24 07:22:46  [info] Applying civicrm_stripe update 1903.  Adding is_live to civicrm_stripe_plans and civicrm_stripe_customers tables.
**Feb 24 07:22:46  [info] Skipped civicrm_stripe update 1903.  Unique key already changed from email to id on civicrm_stripe_plans table.**
Feb 24 07:22:47  [info] Running task: Upgrade com.drastikbydesign.stripe to revision 1_9_003
Feb 24 07:22:47  [info] Running task: Upgrade com.drastikbydesign.stripe to revision 4_6_01
Feb 24 07:22:47  [info] Applying civicrm_stripe update 4601.  Adding processor_id to civicrm_stripe_customers and civicrm_stripe_plans table.
Feb 24 07:22:48  [info] Running task: Upgrade com.drastikbydesign.stripe to revision 4_6_01

As you can see the changing of the index did not take place. When I looked the commit https://github.com/drastik/com.drastikbydesign.stripe/commit/fef3115b60850a999855f3c2f64a8e7543f6e20b I noticed that line 49 of  CRM/Stripe/Upgrader.php references: 

` $sql = "SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = %1 AND TABLE_NAME = 'civicrm_stripe_customers' AND COLUMN_KEY = 'MUL'";`

I suspect that is simply a typo and that it should be Email instead of MUL. 

Hopefully most folks have not waited so long to do the upgrade but fixing it for those who have would be helpful as some folks were having issues as I was getting alleged duplicates in the civicrm_stripe_customers table from some previously existing emails that were added in testing mode.

**Comment by h-c-c** [comment]
Hey @arborrow, don't worry you're fine. This isn't an error...just info.  This db update was already run, and the upgrader script throws this exception when it's run a subsequent time(s).  MUL is a thing.  You can read about MUL keys here: 

https://dev.mysql.com/doc/refman/5.7/en/show-columns.html 

From looking at your logs, apparently when doing a civi update it tries to run all the extension upgrader scripts again.....I say this because it still looks like you're on an old version of the Stripe extension.

**Comment by arborrow** [comment]
Thanks for the prompt reply and reference to MUL - what drew me to that section of code was that in fact the index of the table was still set to email rather than id. After the upgrade, I manually changed it myself since during the upgrade it failed to run. So my concern is that whatever the check is apparently it did not work on my site (and may not on others).

**Comment by arborrow** [comment]
I was previously running CiviCRM 4.4 with the 4.5-dev version of the stripe extension. So it should have changed the index but for whatever reason it failed to actually do so.

**Comment by arborrow** [comment]
p.s. - I am running on a shared host and trying to run the queries against information_schema takes a very long time. I am doing a little testing to see if I can provide more information.

**Comment by arborrow** [comment]
So I went ahead and ran:
SELECT COLUMN_TYPE,COLUMN_KEY,COLUMN_NAME 
FROM information_schema.COLUMNS 
WHERE TABLE_NAME = 'civicrm_stripe_customers' 

and that produced the following:

varchar(64) 		email
varchar(255) 	UNI 	id
tinyint(4) 		is_live
int(10) 		processor_id

So I am confused about the intended behavior. Prior to the update email is the unique index. After the update id is unique index. At what point would there ever by MUL?

**Comment by h-c-c** [comment]
Thanks for thinking about this! 

I don't think the intended behavior is in question so much if you take the comments into consideration, and assume that we meant customers and not plans. :P  Correct me if I'm wrong, I think what you are saying is the (re)implementation can never work, unless a MUL key was added when the table was created or if mysql will creates MUL keys by default.  Neither seems to be the case.    

We could either fix this and not increment.  (That would deal with folks in your situation.)
or fix and increment all of the db numbers. 

I'm inclined towards the first option, since that db upgrade is so ancient and I have a feeling that most users fixed their own databases _if_ they have been hit by this.

**Comment by arborrow** [comment]
I'm inclined to say that because it likely impacts so few people and is pretty easy to fix that we not worry too much about a patch and let this issue and workaround serve as documentation for anyone else who might be impacted. 

By intended behavior I just meant that I didn't see where a non-unique index was ever being created so I couldn't imagine when that condition would ever be met and allow the code to drop the email index and create the id index. Perhaps in other install/upgrade scenarios it created a non-unique (MUL) index but in my situation, as you noted, it just never happened. 

If you choose to fix it, I agree that I wouldn't worry about incrementing. The important thing would be to ensure that if email is still listed as a unique index that it be dropped and perhaps even create a non-unique email index (if there are other queries that might benefit from having it) as well as create the desired unique id index. 

I feel that you understand the situation so I trust whatever you think is the best way forward. Peace - Anthony

**Comment by arborrow** [comment]
@h-c-c  thanks for the latest commit, that should resolve this for anyone else doing the upgrade from an older CiviCRM. I am going to go ahead and close this issue.
