### ISSUE TITLE
BillingBlock.tpl

### ISSUE THREAD

**Issue by laryn** [drastik/com.drastikbydesign.stripe#6]
It looks like the Billing Address checkbox leaves off the state and postal code. Was this BillingBlock.tpl originally part of the default CiviCRM template? The current version of the CiviCRM template looks quite different and my attempt to cut-and-paste the {literal} section from the core Civi version didn't seem to have worked. If I make any progress I'll update here.

**Comment by laryn** [comment]
Also, I'm wondering if it would be possible to use a snippet something like this on an error in a submission:

``` javascript
jQuery('#crm-container').animate({scrollTop: '0px'}, 300);
```

I've heard a few complaints that people try to submit but they don't see the error messages because the form is long enough that the errors messages are off the top of the page and you have to manually scroll up to see them. In the meantime they are just sitting there waiting for a confirmation page.

**Comment by drastik** [comment]
Great idea.

**Comment by laryn** [comment]
What version is the BillingBlock.tpl based off? I will try to look at a diff comparison to see what was changed and perhaps I can do the same changes to the current BillingBlock.tpl (which will hopefully fix the Billing Address checkbox) and I will also add in the snippet above.

**Comment by drastik** [comment]
Well, when this extension started, it was a late 4.1 version, then it rolled into 4.2 and there were no changes.

Late into 4.2 there were some pretty big changes, and I updated the BillingBlock.tpl in either the last version, or the one just before last (1.5 or 1.6).

It appears the tpl may have changed again in 4.3, which is why other issues are showing up.

Here on GitHub, we'll have to split it out to 4.2-x.x  4.3-x.x, and also in Civi repo's.

**Comment by laryn** [comment]
Here's a patch that handles this portion of the issue for 4.3 (scroll to top and the checkbox for Billing address) but doesn't address the other open issue (multiple payment processors functionality).

https://github.com/laryn/civicrm_stripe/blob/patch-1/com.drastikbydesign.stripe/templates/CRM/Core/BillingBlock.tpl
