### ISSUE TITLE
CiviCRM 4.5 compatibility?

### ISSUE THREAD

**Issue by deweydb** [drastik/com.drastikbydesign.stripe#70]
I noticed that the info.xml file over version 1.7 of this plugin says compatibility with CiviCRM 4.4.  Is it not compatible with 4.5?  

Thanks!

**Comment by mlutfy** [comment]
@drastik : I think the issue is that it's been tagged as stable on github (4.5-1.8) but not released on civicrm.org.  If you'd like, you can add your git url in your extension page (https://civicrm.org/extensions/stripe-payment-processor -> edit -> "git url" field) and civicrm.org will automatically publish a new version when a new tag is pushed to git (runs nightly). If you have any issues, feel free to ping me (bgm on IRC) or Nicolas from CiviDesk (who wrote the script).

**Comment by drastik** [comment]
@mlutfy Oh that is sweet!  When did that get added?

Plugging in git URL now.

@deweydb grab the -dev branch for 4.5.

I'll pin a release for 1.8, but it doesn't work in Wordpress currently.

**Comment by mlutfy** [comment]
@drastik : it was added at the 2014 spring post-civicon sprint by Nicolas, but was probably put into production somewhere in late summer. There's also a script that also uses the git url to automatically extracts the ts() strings and sends them to Transifex for translators, then fetches those strings and generates the binary .mo files automatically on a nightly basis. (https://www.transifex.com/projects/p/civicrm_extensions/resources/) :)

**Comment by crusonweb** [comment]
Any idea when the 4.5 version will be working in Wordpress?  Or any guidance on why it is not working so that I can look into making it work?  I have two clients which upgraded Civi to 4.5 without checking whether Stripe would be compatible and now are stuck.

**Comment by drastik** [comment]
@crusonweb 
Ugh, what _is_ working in Wordpress :(
It's all crapped up.  What I know isn't working:
- stripe_token missing because it can't insert JS from Civi like Drupal, 
- The cancel / error return URLs aren't working.

It can't do things that Civi intends for its host CMS to do, so I don't see how it will work properly without a lot of hand-holding (and ugly coding) specifically for WP.  
I am not familiar enough with WP to confidently say when it is working or that I have done it correctly.  It would be nice if a WP dev could speak to solutions / work-arounds for the shortcomings in features.

**Comment by crusonweb** [comment]
Thanks, those are the two issues I'm seeing, and it gives me a place to start.  I'm not familiar enough with Stripe to know why the token is missing and that is the main problem (I can live with the cancel/error return URLs not working for now).  

Where does the JS need to be inserted?  I looked at the source of the contribution page and it looked like the call to the .js file was being called within the body of the form.  Does it need to be loading somewhere else for the token to be retrieved?  It looks like Stripe's documentation says it needs to be in the head of the page but it looked like you purposely put it lower down so I wasn't sure.

P.S. Just for the sake of completeness, I did disable the JS portion and it does still work in the less PCI Compliant way.  So it appears things still work properly for the most part.

**Comment by drastik** [comment]
_Where does the JS need to be inserted?_
Doesn't matter whether `<head> or <body>`.
It is coming out in `<body>` because it is being dynamically added in a Civi buildForm hook, and this is where Civi is outputting it.  That is to say, it is added when we are on a CiviCRM form that uses the Stripe payment processor.

I don't know why, or entirely how, since Drupal has functions that could still get the script inserted into `<head>` any time during PHP logic for page generation.
If WP has a function similar to Drupal's `drupal_add_js()` or the `#attached js` mechanism, that might be a solution.

**Comment by crusonweb** [comment]
There are a couple of similar ones.  I will play around with it and see what I can come up with.

**Comment by deweydb** [comment]
Like crusonweb said, the js is getting inserted properly. But there is a difference in jquery version between Wordpress and Drupal, so the $().submit() form submit binding isn't working, I changed it to a .click on the submit button instead and this solved my problems.

Response Written on a tablet, When I get to my desktop computer I can share the relevant code.

**Comment by crusonweb** [comment]
Thanks deweydb, if you could share that when you get a chance that would be great.

**Comment by deweydb** [comment]
in civicrm_stripe.js

I changed:
https://gist.github.com/deweydb/e874cbca9a32b54d9e5b
to:
https://gist.github.com/deweydb/0c8f48dca49a2e83260a

**Comment by drastik** [comment]
What if I hit `return` / Enter on the form?

**Comment by deweydb** [comment]
Hmm yeah, i think maybe my solution isn't perfect, not sure why, but the existing code would not submit at all.

**Comment by deweydb** [comment]
Oh, i think i know why, because .submit is short form for .on( "submit", handler ), and .on changed in jQuery 1.7:
it should be something like:
$form.on('submit', $form.parent() ,function(event){

**Comment by deweydb** [comment]
I noticed something else that is broken in this file today.  If you have more than one payment processor, this check:

```
      if ($form.find(".crm-section.payment_processor-section").length > 0) {
        if (!($form.find('input[name="hidden_processor"]').length > 0)) {
          return true;
        }
      }
```

does not work, maybe that hidden_processor name is not applied in 4.5?
I ended up changing it to this (i know this is totally hacky, but i needed it to work today, would be interested in hearing a better solution)

```
  if ($form.find(".crm-section.payment_processor-section").length > 0) {
            var processor = $('.payment_processor-section input:checked').attr('id');
            if(processor != 'CIVICRM_QFID_3_payment_processor'){
                submitOnce(this,'Main','Processing');
                return true;
            }      
  }
```

Please forgive me for my noobishness i only just recently started working with civi and don't know that much about how it works.

**Comment by drastik** [comment]
Try again with 1.9.1 and let me know of any issues.
Working for myself and others.
